### ISSUE TITLE
又报错了…明明已经配置了变量

### ISSUE THREAD

**Issue by gky008** [x2rr/state-grid#2]
/bin/bash: line 2: _1/2024-12-20-17-35-18-115.log: No such file or directory
/bin/bash: line 3: LICENSE: command not found
/bin/bash: line 4: LICENSE: command not found
/bin/bash: line 5: 修改适配homeassistant，通过mqtt发送消息至homeassistant: command not found
/bin/bash: line 6: LICENSE: command not found
/bin/bash: line 7: 环境变量设置: command not found
/bin/bash: line 15: LICENSE: command not found
/bin/bash: line 16: LICENSE: command not found
/bin/bash: line 17: LICENSE: command not found
/bin/bash: line 18: 脚本声明:: command not found
/bin/bash: line 19: 1.: command not found
/bin/bash: line 20: 2.: command not found
/bin/bash: line 21: 3.: command not found
/bin/bash: line 22: 4.: command not found
/bin/bash: line 23: 5.: command not found
/bin/bash: line 24: 6.: command not found
/bin/bash: line 25: 7.: command not found
/bin/bash: line 26: LICENSE: command not found
/bin/bash: line 27: LICENSE: command not found
/bin/bash: line 28: back/: Is a directory
/bin/bash: -c: line 29: syntax error near unexpected token `('
/bin/bash: -c: line 29: `const getEnv = () =>'

**Comment by xiaodai00** [comment]
/osg-open-uc0001/member/c4/f02,
## 开始执行... 2024-12-20 23:21:42



[网上国网] [ERROR]
TypeError: dayList.filter is not a function

## 执行结束... 2024-12-20 23:21:43  耗时 1 秒




出现这个问题是什么情况？

**Comment by x2rr** [comment]
> /bin/bash：第 2 行：_1/2024-12-20-17-35-18-115.log：没有这样的文件或目录 /bin/bash：第 3 行：许可证：找不到命令 /bin/bash：行4: LICENSE: command not find /bin/bash: line 5: 修改车辆homeassistant，通过mqtt发送消息至homeassistant: command not find /bin/bash: line 6: LICENSE: 命令未找到 /bin/bash: 第 7 行: 环境变量设置: 命令未找到 /bin/bash: 第 15 行: LICENSE: 命令未找到 /bin/bash: 第 16 行: LICENSE: 命令未找到 /bin /bash: 第 17 行: 许可证: 未找到命令 /bin/bash: 第 18 行: 脚本声明:: 未找到命令 /bin/bash: 第 19 行: 1.: 未找到命令 /bin/bash：第 20 行：2.：未找到命令 /bin/bash：第 21 行：3.：未找到命令 /bin/bash：第 22 行：4.：未找到命令 /bin/bash：第 23 行： 5.：未找到命令 /bin/bash：第 24 行：6.：未找到命令 /bin/bash：第 25 行：7.：未找到命令 /bin/bash： 第 26 行：LICENSE：未找到命令 /bin/ bash：第 27 行：LICENSE：未找到命令 /bin/bash：第 28 行：back/：是目录 /bin/bash：-c：第 29 行：意外标记附近出现语法错误`(' /bin/bash: -c: line 29: `const getEnv = () =>'

看日志这不像青龙环境
