### ISSUE TITLE
这个是什么情况

### ISSUE THREAD

**Issue by xiaodai00** [x2rr/state-grid#4]
开始执行
... 2024-12-20 18:49:03
【网上国网][ERRORJ
TypeError: dayList.filter is not a functio
##执行结束
2024-12-20 18:49:04
耗时1s

**Comment by x2rr** [comment]
未正确配置环境变量

**Comment by xiaodai00** [comment]
> 未正确配置环境变量
怎么操作呢  麻烦解答下

**Comment by x2rr** [comment]
> > 未正确配置环境变量
> > 怎么操作呢  麻烦解答下

在青龙-配置文件-config.sh中，正确填写以下信息
``` 
export WSGW_USERNAME="" #网上国网账号
export WSGW_PASSWORD="" #网上国网密码
export WSGW_RECENT_ELC_FEE="true" #是否获取最近电费
export WSGW_mqtt_host="" #mqtt服务器地址 192.168.1.7
export WSGW_mqtt_port="" #mqtt服务器端口 1883
export WSGW_mqtt_username="" #mqtt服务器用户名
export WSGW_mqtt_password="" #mqtt服务器密码
```

**Comment by xiaodai00** [comment]
> > > 未正确配置环境变量
> > > 怎么操作呢  麻烦解答下
> 
> 在青龙-配置文件-config.sh 中，正确填写以下信息
> 
> ```
> export WSGW_USERNAME="" #网上国网账号
> export WSGW_PASSWORD="" #网上国网密码
> export WSGW_RECENT_ELC_FEE="true" #是否获取最近电费
> export WSGW_mqtt_host="" #mqtt服务器地址 192.168.1.7
> export WSGW_mqtt_port="" #mqtt服务器端口 1883
> export WSGW_mqtt_username="" #mqtt服务器用户名
> export WSGW_mqtt_password="" #mqtt服务器密码
> ```

我都设置都是对的呢 怎么还是一样呢
